### ISSUE TITLE
Feature: allowing docker-compose.override.yml file

### ISSUE THREAD

**Issue by jtdevops** [datastack-net/dockerized#19] opened 2022-03-25 18:43 UTC
Hi,

When the docker-compose command is run it will use the docker-compose.yml and docker-compose.override.yml file, and combine their configurations.
Could this be added to this projects?

This would allow me to have my own docker-compose.override.yml file which would be combined with the default configuration of dockerized, and allowing me to easily upgrade without worrying about overwriting my own local changes.

**Comment by boukeversteegh** [comment] 2022-03-25 19:48
Hi @jtdevops!

That's a feature request I was sort of expecting already, as it would allow:

- Customization of commands (such as mounting extra directories, or overriding base images)
- Extending dockerized with extra commands that are very project specific

However, you mention your need for this feature is to avoid overwriting local changes. Do you mean local changes to `dockerized/docker-compose.yml`, which you did to allow those above improvements? Just clarifying to be sure I understand the use-case 100%.

Requirements proposal:

1. Dockerized will not automatically pick up local docker-compose files, without explicit opt-in.
  - This is to prevent scenarios where dockerized is run in a directory where an unrelated docker-compose file exists, which could breaks dockerized or causes unpredictable behavior.
2. The user can specify one or multiple docker-compose file that will be merged with the base config.
3. Relative volume mounts specified in the overriding docker-compose file, should be relative to the user's .yml file, not dockerized.

About the implementation, I have the following in mind:

1. `dockerized/docker-compose.yml` is always the base config file.
2. The project directory may contain a `docker-compose.dockerized.yml` file, which will automatically be loaded (merged).
3. The user can specify another extra config file, in `dockerized.env`. For example:
   ```dotenv
   COMPOSE_FILE=docker-compose.override.yml
   ```
4. Currently, docker-compose runs with the `dockerized/` folder as the 'compose project working dir', so that volume mounts are relative to that directory.
  1. To allow relative mounts defined by the user, dockerized will read the user's docker-compose file, and convert the relative mounts to absolute paths (e.g. './app' --> '/home/project1/app')

Curious to hear what you think. Especially, do you agree with requirement 1? Or would you rather assume that all docker-compose files would be picked up?

What sort of customization have you currently done? Was there a reason to keep those changes local, rather than making a PR for them? Thanks in advance for sharing!

**Comment by jtdevops** [comment] 2022-03-25 21:19
Thanks for the quick reply. I like your thinking. :)

- The dockerized/docker-compose.yml is the base file
- If there is a dockerized/docker-compose.override.yml file, then merge this file with the base file.
- I never thought about this, but If there is a project specific file docker-compose.dockerized.yml then also merge this with the previous ones, and ignore any project specific docker-compose.yml files

I am using Windows 10 with WSL, and my current issues I have noticed since I started using dockerized 2 releaes ago are:
- I made changes to the dockerized/docker-compose.yml file to add additional volumes to the 'ansible' service so that I could map my ~/.ssh folder into the ansible container. Upgrading to your latest release(s) takes a bit of effort as I need to merge my changes back into your docker-compose.yml file after.
- I have built a custom docker image with all of the development tools that I use in my workflow. I have also added this to your dockerized/docker-compose.yml file, but adding it to dockerized/docker-compose.override.yml would be better since this file wouldn't be bundled with your app/release.

I would also like to see if you might be able to help with file permission issues for WSL files and using volume mounts.
As mentioned above I need to add my ~/.ssh folder into the ansible container. However ssh complains that the files are 'rwxrwxrwx' and refuses to use them.
I also have an ansible.cfg file in the root of my ansible project, and ansible also refuses to load this file for the same reason.

To get around the .ssh folder issue, I have created a named volume and added the needed .ssh files and also changed their permissions. Now when the container runs ssh doesn't complain as the permissions are set to 600.
I am still trying to work on getting the ansible.cfg file working though, as this might be project specific.

Do you have any idea on how to get something like this working and easily updateable?
Could you maybe provide an option for the dockerized command to build a home/root volume that would include and change permissions as needed?

Thanks for such a great project.

**Comment by boukeversteegh** [comment] 2022-03-25 23:07
>     * If there is a dockerized/docker-compose.override.yml file, then merge this file with the base file.
>     * I never thought about this, but If there is a project specific file docker-compose.dockerized.yml then also merge this with the previous ones, and ignore any project specific docker-compose.yml files

Ah, I see now, that you primarily need a method to globally customize the commands in dockerized. Not per project.

Clearly, changing the actual source-code is not a good long-term solution. The suggestion to do this was actually a mistake, as it was intended to help users contribute to dockerized, rather than to show how to add commands locally. But it was worded as such, and with no alternative you now ended up with this merge conflict 🤦‍♂️. Sorry for that!

For the future, I think it will be safer to keep user-data separate from the source code.

Thinking about it, some services also already mount directories in `~/.dockerized/apps/`. Since there are now 3 pieces of global user-data (dockerized.env file, yaml file, volume data), I think it will be better to keep all of it in one directory.

So the iterated functional proposal would be:

- The `dockerized/docker-compose.yml` is the base file (unchanged)
- If there is a `~/.dockerized/docker-compose.yml` file, then merge this file with the base file. (name could be `docker-compose.override.yml` to emphasize that it doesn't need to be a "complete" yml file)
- All mounted volumes specified in the user yml, should be absolute paths.
  - This will allow delegating the merging directly to docker-compose without manually fixing paths and merging the files.

I propose to split off the project specific docker-compose file for now, to keep the iteration small. So, no special new Env vars that specify the config file.


---

> I am using Windows 10 with WSL, and my current issues I have noticed since I started using dockerized 2 releaes ago are:
> 
>     * I made changes to the dockerized/docker-compose.yml file to add additional volumes to the 'ansible' service so that I could map my ~/.ssh folder into the ansible container. Upgrading to your latest release(s) takes a bit of effort as I need to merge my changes back into your docker-compose.yml file after.
>     * I have built a custom docker image with all of the development tools that I use in my workflow. I have also added this to your dockerized/docker-compose.yml file, but adding it to dockerized/docker-compose.override.yml would be better since this file wouldn't be bundled with your app/release.

Thanks for the details of your use-case! This indeed points to the need of local customization, which is separate from contributing to dockerized.

> I would also like to see if you might be able to help with file permission issues for WSL files and using volume mounts. As mentioned above I need to add my ~/.ssh folder into the ansible container. However ssh complains that the files are 'rwxrwxrwx' and refuses to use them. I also have an ansible.cfg file in the root of my ansible project, and ansible also refuses to load this file for the same reason.

I'd recommend to have a look at https://docs.docker.com/compose/compose-file/compose-file-v3/#long-syntax
You can mount volumes in readonly mode and override the permission mode.

> 
> To get around the .ssh folder issue, I have created a named volume and added the needed .ssh files and also changed their permissions. Now when the container runs ssh doesn't complain as the permissions are set to 600. I am still trying to work on getting the ansible.cfg file working though, as this might be project specific.
> 
> Do you have any idea on how to get something like this working and easily updateable? Could you maybe provide an option for the dockerized command to build a home/root volume that would include and change permissions as needed?

Thanks for sharing. It will help to make dockerized work in more environments. I've mostly tested on Windows using git-bash, and will have a look this weekend if I can get ansible to work right.

If you need any initialization logic in your containers, you could have a look at:

- [gh](https://github.com/datastack-net/dockerized/blob/070c1f5c3e140e73ede21cde6430d7e3a1e97864/apps/gh/)
- https://github.com/datastack-net/dockerized/blob/070c1f5c3e140e73ede21cde6430d7e3a1e97864/docker-compose.yml#L61-L75

I'm currently in doubt whether it makes sense to have 1 single dockerized HOME directory, in which all dockerized commands can read/write their config (including .ssh). It breaks isolation between projects, and commands may break when they share the same HOME dir (for example, a `~/.bashrc` file that may work on ubuntu but not alpine). So it would imply different directories per command, and per project if needed. Something to keep thinking about.

If you have a working solution, I'd be glad to know what it looks, and see how dockerized can accommodate those solutions for other commands as well. In general I'd like commands such as `ansible` to work out of the box, without special efforts, and similar to the native commands, as stated in the Design goals.

> Thanks for such a great project.

Glad to hear your feedback!

**Comment by boukeversteegh** [comment] 2022-03-28 13:45
I've implemented the ability to override / extend the compose file.

Please see the new readme.

If there are any difficulties with it, or questions, feel free to open another issue.

**Comment by jtdevops** [comment] 2022-03-28 20:11
Hi,
I am having some issues when use the global home directory 'dockerized.env' file and a per project 'dockerized.env' file.

The per project configuration seems to be overriding the global configuration that I have set.
I am using Windows 10 command prompt

# ~/dockerized.env (C:\Users\<user>\dockerized.env)
```
HOME=${HOMEPATH}
COMPOSE_FILE="${COMPOSE_FILE};${HOME}/docker-compose.dockerized.yml"
```

# ~/docker-compose.dockerized.yml
```
version: "3"
services:
  dev:
    image: "my-project-build-env"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    entrypoint: [ "/bin/bash" ]
```

From within any folder, the following always works:
```
dockerized dev
```

# C:\my-project\dockerized.env
```
COMPOSE_FILE="${COMPOSE_FILE};${DOCKERIZED_PROJECT_ROOT}/docker-compose.dockerized.yml"
```

# C:\my-project\docker-compose.dockerized.yml
```
version: "3"
services:
  ansible: &ansible
    image: "willhallonline/ansible:${ANSIBLE_VERSION}-${ANSIBLE_BASE}"
    entrypoint: [ "/init.sh", "ansible" ]
    volumes:
      - "${HOME}/.ssh:/dockerized/host/home/.ssh"
      - ./apps/ansible/init.sh:/init.sh
  ansible-playbook:
    <<: *ansible
    entrypoint: [ "/init.sh", "ansible-playbook" ]
    environment:
      - ANSIBLE_CONFIG=ansible.cfg
```

From within my project folder, running ansible works
```
dockerized ansible localhost -m ping
```

However running the 'dev' service fails:
```
C:\my-project>dockerized dev
[+] Running 0/1
 - dev Error                                                                                                                           1.1s
```

Using the 'dockerized.env' files above, it allows me to set a specific HOME variable for the CMD prompt, without affecting the WSL HOME variable as the users home paths are different for each prompt.

**Comment by boukeversteegh** [comment] 2022-03-28 21:34
There was indeed a problem in the code. Fixed!

**Closed by boukeversteegh** 2022-03-28 21:34 UTC
